global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    datacenter: primary

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alert-manager-0-27:9093

rule_files:
   - /opt/bitnami/prometheus/conf/rules.yaml
   - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'federation'
    scrape_interval: 20s
    scrape_timeout: 20s
    scheme: https
    metrics_path: /federate
    honor_labels: true
    params:
      match[]:
        - '{job=~"kube-state-metrics|kubernetes-cadvisor|nodejs|rabbitmq_exporter|redis"}'
    static_configs:
      - targets : 
        - 'mm-poc-prometheus.lowtouchcloud.io:443'
  
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['10.0.2.2:9100', '10.0.1.2:9100', '23.239.11.221:9100', '45.56.110.158:9100', '23.92.22.28:9100', '50.116.54.235:9100', '45.56.110.157:9100', '172.104.9.7:9100', '172.104.9.43:9100', '172.104.9.9:9100', '66.175.214.162:9100', '45.79.185.151:9100', '198.74.57.170:9100', '45.33.83.95:9100' ]
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(engine.master)'
        target_label: nodename
        replacement: cloudorbit-${1}
      - source_labels: ['nodename']
        regex: 'k8s.(.*)'
        target_label: nodename
        replacement: cloudorbit-${1}
      - source_labels: ['nodename']
        regex: 'lke415125-625416-0dea598d0000'
        target_label: nodename
        replacement: poc-worker-1
      - source_labels: ['nodename']
        regex: 'lke415125-625416-29eb814d0000'
        target_label: nodename
        replacement: poc-worker-2
      - source_labels: ['nodename']
        regex: 'lke415125-625416-3c0f0b4f0000'
        target_label: nodename
        replacement: poc-worker-3
      - source_labels: ['nodename']
        regex: 'lke415125-625416-3e159e4e0000'
        target_label: nodename
        replacement: poc-worker-4
      - source_labels: ['nodename']
        regex: 'lke415125-625416-43338bb50000'
        target_label: nodename
        replacement: poc-worker-5
      - source_labels: ['nodename']
        regex: 'lke415125-633537-22395f250000'
        target_label: nodename
        replacement: poc-worker-6
      - source_labels: ['nodename']
        regex: 'lke415125-633537-4aa6830d0000'
        target_label: nodename
        replacement: poc-worker-7
      - source_labels: ['nodename']
        regex: 'lke415125-633537-5e3bd6120000'
        target_label: nodename
        replacement: poc-worker-8
      - source_labels: ['nodename']
        regex: 'lke415125-650491-02f85d070000'
        target_label: nodename
        replacement: poc-worker-9
      - source_labels: ['nodename']
        regex: 'lke415125-650491-0cdc53a00000'
        target_label: nodename
        replacement: poc-worker-10
      - source_labels: ['nodename']
        regex: 'lke415125-650491-124a48e20000'
        target_label: nodename
        replacement: poc-worker-11
      - source_labels: ['nodename']
        regex: 'lke415125-650491-45b4ea2c0000'
        target_label: nodename
        replacement: poc-worker-12

  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    
