global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    datacenter: primary

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alert-manager-0-27:9093

rule_files:
   - /opt/bitnami/prometheus/conf/rules.yaml
   - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'federation'
    scrape_interval: 20s
    scrape_timeout: 20s
    scheme: https
    metrics_path: /federate
    honor_labels: true
    params:
      match[]:
        - '{job=~"kube-state-metrics|kubernetes-cadvisor|nodejs|rabbitmq_exporter|redis"}'
    static_configs:
      - targets : 
        - 'mm-poc-prometheus.lowtouchcloud.io:443'
  
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['10.0.1.2:9100', '10.0.2.2:9100', '192.168.148.48:9100', '192.168.132.65:9100', '192.168.195.31:9100', '192.168.196.206:9100', '192.168.195.98:9100']
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(engine.master)'
        target_label: nodename
        replacement: cloudorbit-${1}
      - source_labels: ['nodename']
        regex: 'k8s.(.*)'
        target_label: nodename
        replacement: cloudorbit-${1}
      - source_labels: ['nodename']
        regex: 'lke415125-625416-0dea598d0000'
        target_label: nodename
        replacement: poc-worker-1
      - source_labels: ['nodename']
        regex: 'lke415125-625416-3e159e4e0000'
        target_label: nodename
        replacement: poc-worker-2 
      - source_labels: ['nodename']
        regex: 'lke415125-625416-43338bb50000'
        target_label: nodename
        replacement: poc-worker-3
      - source_labels: ['nodename']
        regex: 'lke415125-625416-3c0f0b4f0000'
        target_label: nodename
        replacement: poc-worker-4
      - source_labels: ['nodename']
        regex: 'lke415125-625416-29eb814d0000'
        target_label: nodename
        replacement: poc-worker-5

  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    
