global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alert-manager-0-27:9093

rule_files:
   - /opt/bitnami/prometheus/conf/rules.yaml
   - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['192.168.144.204:9100', '192.168.144.198:9100', '192.168.144.151:9100', '172.233.193.238:9100']
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(engine.master)'
        target_label: nodename
        replacement: appz-${1}
      - source_labels: ['nodename']
        regex: 'k8s.worker.node.(.*)'
        target_label: nodename
        replacement: appz-dev-worker-${1}
  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    
  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
     module: [tcp_connect] 
    static_configs:
    - targets:
       - 172.20.22.64:3306

       
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115  
      
      
